version: '3'
services:

  spark:
    image: marcorezende/jupyter-pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - AWS_ACCESS_KEY_ID=TESTE123
      - AWS_SECRET_ACCESS_KEY=TESTE123
      - ENDPOINT_URL=http://minio:9000
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage_demo:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data


volumes:
  minio_storage_demo: {}